# SQLALCHEMY connection url.  Note that using sqlite has serious limits WRT to
# alembic migrations support (so it is discouraged in production).
db_url: 'sqlite:////tmp/resalloc-db.sqlite'

# Where the main logging output goes.
main_logfile: '/var/log/resallocserver/main.log'
