# SQLALCHEMY connection url.  Note that using sqlite has serious limits WRT to
# alembic migrations support (so it is discouraged in production).  Make sure
# you have installed appropriate libraries for desired SQL dialect, for
# appropriate python version!
#
#For PostgreSQL connection without password using unix socket auth method.
#db_url: 'postgresql://resalloc@/resalloc'
#For PostgreSQL listening on host/port, using password.
#db_url: 'postgresql://resalloc:pass@localhost:5432/resalloc'
db_url: 'sqlite:////tmp/resalloc-db.sqlite'

# Where the main logging output goes.
main_logfile: '/var/log/resallocserver/main.log'

# Hostname to make the xmlrpc server listen on.
#hostname: 'localhost'

# Port to make the xmlrpc server listen on.
#port: 49100
